# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7b0f52a3f9dfcc29cba1dd7d835c731a3d1019448810c6f22440d7fd2109018330a69d22867d6c3560505b0930ab66440ec867aedee320c183ea880bdd6bc22

test:
  secret_key_base: 1e2941b68ef2f3a1065cf92fb53ae8f530eaa82d0ccf3106e9b823e7aaca3331b1c62197417d87da1ad5da68978d23ee7a26bbf095d60fab383cfedfa453b655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
